esphome:
  name: riego-cantero

esp8266:
  board: esp01_1m

# Enable logging
logger:

switch:
  - platform: gpio
    pin: 0
    name: "Valvula"
    inverted: true
# Enable Home Assistant API
api:

ota:
  password: "978e4a201772929b56bcf1dc7bcfddb9"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Riego-Cantero Fallback Hotspot"
    password: "LOZgkqxZpEq1"

captive_portal:
